'use client'

import Image from 'next/image'
import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowDown, ArrowRight, AtSign, CalendarDays, CirclePlay, Compass, Globe, Handshake, MapPin, Menu, Megaphone, MessageCircle, Orbit, Puzzle, Rocket, Send, Sparkles, Users, Video, X, Zap } from 'lucide-react'

const navItems = ['Home', 'About', 'The Hackathon', 'Challenges', 'Community', 'Sponsors', 'Team']
const features = [
  ['THE HACKATHON', '48 hours of creation, collaboration and fun', '01'],
  ['CHALLENGES', 'Real problems from space agencies & NASA data', '02'],
  ['WHO CAN JOIN?', 'Anyone. Anywhere. Any background.', '03'],
  ['OUR COMMUNITY', 'A global network of dreamers and builders', '04'],
]
const speakers = ['ORBITAL MIND', 'DATA NAVIGATOR', 'MISSION BUILDER', 'COSMIC GUIDE']
const partnerTypes = [
  ['Financial', Handshake], ['In-Kind', Puzzle], ['Strategic', Handshake], ['Media', Megaphone],
]

function Reveal({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .7, delay, ease: [.22, 1, .36, 1] }}>{children}</motion.div>
}

function Logo() {
  return <a href="#home" className="flex items-center gap-3" aria-label="NASA Space Apps home"><span className="logo-mark"><Rocket size={19} strokeWidth={1.7} /></span><span><span className="block font-display text-sm font-bold tracking-[.16em] text-white">NASA SPACE APPS</span><span className="block text-[9px] tracking-[.28em] text-fuchsia-300">6TH OF OCTOBER</span></span></a>
}

function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p> }
function GradientText({ children }: { children: React.ReactNode }) { return <span className="gradient-text">{children}</span> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [tab, setTab] = useState('INDUSTRY LEADERS')
  return <main id="home" className="min-h-screen overflow-hidden bg-[#05070f] text-white">
    <header className="nav-shell"><div className="container nav-inner"><Logo /><nav className="desktop-nav">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replaceAll(' ', '-')}`} className="nav-link">{item}</a>)}</nav><a className="gradient-button nav-cta" href="#join">JOIN THE MISSION <ArrowRight size={15} /></a><button className="icon-button menu-toggle lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="mobile-menu lg:hidden">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a href="#join" className="gradient-button">JOIN THE MISSION <ArrowRight size={15} /></a></nav>}</header>

    <section className="hero-section"><div className="starfield" /><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><Image src="/space-hero.png" alt="Astronaut looking over a glowing planet horizon" fill priority className="hero-image" /><div className="hero-vignette" /><div className="container hero-inner"><Reveal className="hero-copy"><SectionLabel>EXPLORE · INNOVATE · IMPACT</SectionLabel><h1 className="hero-title mt-5">JOIN NASA<br /><GradientText>SPACE APPS</GradientText><br /><span className="text-white/90">6TH OF OCTOBER</span> <GradientText>2026</GradientText></h1><p className="hero-description mt-7 max-w-xl text-base leading-7 text-slate-300 md:text-lg">What if this weekend, your idea stopped being just an idea? Step up, build, and solve real-world challenges using NASA&apos;s open data.</p><div className="hero-actions mt-9 flex flex-wrap gap-4"><a href="#join" className="gradient-button">REGISTER NOW <ArrowRight size={16} /></a><a href="#the-hackathon" className="outline-button"><CirclePlay size={17} /> SECURE YOUR SPOT</a></div></Reveal><Reveal delay={.18} className="hero-event"><div className="date-card"><div className="mb-8 flex items-start justify-between"><CalendarDays className="text-fuchsia-300" size={22} /><span className="rounded-full border border-fuchsia-400/30 px-2 py-1 text-[9px] tracking-[.18em] text-fuchsia-200">LIVE EVENT</span></div><p className="font-display text-2xl font-bold">NOV 14–15, 2026</p><div className="mt-4 flex gap-2 text-sm text-slate-300"><MapPin size={16} className="mt-0.5 shrink-0 text-blue-300" />6th of October City,<br />Giza, Egypt</div></div></Reveal></div><a href="#about" className="scroll-cue"><span>SCROLL TO EXPLORE</span><ArrowDown size={16} /></a></section>

    <section className="stats-section container relative z-20 -mt-10"><Reveal><div className="stats-panel grid divide-y divide-white/10 md:grid-cols-3 md:divide-x md:divide-y-0">{[['1,000+', 'INNOVATORS EXPECTED'], ['48 HOURS', 'OF CONTINUOUS INNOVATION'], ['1 GLOBAL', 'MISSION']].map(([a,b], i) => <div key={b} className="flex items-center gap-4 px-7 py-6 md:justify-center"><span className="stat-icon">{i === 0 ? <Users size={17} /> : i === 1 ? <Zap size={17} /> : <Orbit size={17} />}</span><div><strong className="font-display text-lg">{a}</strong><p className="mt-1 text-[10px] tracking-[.18em] text-slate-400">{b}</p></div></div>)}</div></Reveal></section>

    <section id="about" className="mission-section section-space container"><div className="grid items-center gap-16 lg:grid-cols-[.8fr_1.2fr]"><Reveal><SectionLabel>WHY SPACE APPS?</SectionLabel><h2 className="section-title mt-4">SOLVING GLOBAL<br /><GradientText>CHALLENGES</GradientText><br />WITH LOCAL TALENT</h2><p className="mt-6 max-w-md leading-7 text-slate-400">The newest branch in Egypt — your closest shot at global recognition, collaboration, and real-world impact.</p><a href="#the-hackathon" className="text-link mt-8 inline-flex">DISCOVER THE EXPERIENCE <ArrowRight size={15} /></a></Reveal><Reveal delay={.12}><div className="mission-skills planet-row">{[['CODE','BUILD'],['DESIGN','CREATE'],['DATA','ANALYZE'],['CREATE','IMAGINE'],['SOLVE','IMPACT']].map(([a,b], i) => <div key={a} className="planet-node"><span className={`planet planet-${i+1}`}><span /></span><p>{a}<br /><GradientText>{b}</GradientText></p></div>)}</div></Reveal></div></section>

    <section id="the-hackathon" className="section-space container"><Reveal><SectionLabel>THE MISSION CONTROL</SectionLabel><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><h2 className="section-title">ONE WEEKEND.<br /><GradientText>ENDLESS POSSIBILITIES.</GradientText></h2><p className="max-w-sm pb-1 text-sm leading-6 text-slate-400">Everything you need to move from a bold idea to a solution that matters.</p></div></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([title, desc, n], i) => <Reveal key={title} delay={i * .08}><article className="feature-card"><div className={`feature-art art-${i+1}`}><span>{n}</span><div className="art-grid" /></div><div className="p-5"><h3 className="font-display text-sm font-bold tracking-[.08em]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{desc}</p><a className="round-arrow mt-5" href={title === 'THE HACKATHON' ? '#the-hackathon' : title === 'CHALLENGES' ? '#challenges' : title === 'WHO CAN JOIN?' ? '#join' : '#community'} aria-label={`Learn more about ${title}`}><ArrowRight size={15} /></a></div></article></Reveal>)}</div></section>

    <section id="community" className="section-space container"><Reveal><div className="max-w-3xl"><SectionLabel>THE PEOPLE BEHIND THE MISSION</SectionLabel><h2 className="section-title mt-4">MEET OUR INSPIRING<br /><GradientText>SPEAKERS & MENTORS</GradientText></h2><p className="mt-6 max-w-xl leading-7 text-slate-400">Guided by industry leaders, space scientists, and tech pioneers ready to help you refine your ideas, troubleshoot your code, and craft winning solutions.</p></div></Reveal><div className="mt-10 flex gap-2 rounded-full border border-white/10 bg-white/[.03] p-1 w-fit">{['INDUSTRY LEADERS','TECHNICAL GUIDES'].map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`tab-button ${tab === item ? 'active' : ''}`} aria-pressed={tab === item}>{item}</button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{speakers.map((name, i) => <Reveal key={name} delay={i*.08}><div className="speaker-card"><div className={`speaker-art speaker-${i+1}`}><div className="silhouette"><Users size={58} strokeWidth={.7} /></div><span className="absolute left-4 top-4 text-[10px] tracking-[.18em] text-white/60">0{i+1}</span></div><div className="border-t border-white/10 p-4"><p className="font-display text-xs font-bold tracking-[.12em]">{name}</p><p className="mt-2 text-[10px] tracking-[.14em] text-fuchsia-300">ANNOUNCEMENT COMING SOON</p></div></div></Reveal>)}</div></section>

    <section id="sponsors" className="section-space container"><Reveal><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>JOIN THE ECOSYSTEM</SectionLabel><h2 className="section-title mt-4">BACKED BY VISIONARIES &<br /><GradientText>INDUSTRY LEADERS</GradientText></h2><p className="mt-6 max-w-md leading-7 text-slate-400">Be part of a movement that turns curiosity into capability, and local talent into global impact.</p></div><div><div className="partner-card"><div className="must-mark">M</div><div><p className="font-display text-lg font-bold tracking-[.1em]">MUST University</p><p className="mt-1 text-sm text-slate-400">Proposed Founding Strategic Partner</p></div><Sparkles className="ml-auto text-fuchsia-300" /></div><p className="mt-10 mb-4 text-[10px] tracking-[.2em] text-slate-500">BECOME A PARTNER</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{partnerTypes.map(([label, Icon]) => <a href="#join" key={label as string} className="partner-type"><Icon size={19} /><span>{label as string}</span></a>)}</div></div></div></Reveal></section>

    <section id="challenges" className="section-space container"><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Reveal><div className="venue-copy"><SectionLabel>THE LAUNCHPAD</SectionLabel><h2 className="section-title mt-4">EXPERIENCE THE ENERGY<br /><GradientText>AT 6TH OF OCTOBER</GradientText></h2><p className="mt-6 max-w-lg leading-7 text-slate-400">A campus built for connection, a city built for possibility. Find your people, your team, and your next big idea in the heart of Egypt&apos;s innovation district.</p><div className="mt-7 flex gap-3 text-sm leading-6 text-slate-300"><MapPin className="mt-1 shrink-0 text-fuchsia-300" size={18} />MUST University Campus, Al Motamayez District,<br />6th of October City, Giza, Egypt</div><div className="map-card mt-9"><div className="map-lines" /><div className="map-pin"><MapPin size={22} /></div><div className="absolute bottom-4 left-4"><p className="font-display text-xs tracking-[.15em]">INTERACTIVE VENUE MAP</p><p className="mt-1 text-[10px] text-slate-400">LOGISTICS GUIDE · OPEN IN MAPS <ArrowRight className="inline" size={12} /></p></div></div></div></Reveal><Reveal delay={.12}><div className="highlights-card"><div className="mb-5 flex items-center justify-between"><SectionLabel>FIELD NOTES</SectionLabel><span className="text-[10px] tracking-[.15em] text-slate-500">COMING SOON</span></div><h3 className="font-display text-2xl font-bold">PHOTOS & HIGHLIGHTS<br /><GradientText>FROM THE MISSION</GradientText></h3><div className="mt-8 grid grid-cols-3 gap-2">{Array.from({length: 6}).map((_, i) => <div key={i} className={`thumb thumb-${i+1}`}><span>{String(i+1).padStart(2,'0')}</span></div>)}</div></div></Reveal></div></section>

    <section id="join" className="container pb-24"><Reveal><div className="join-panel"><div><SectionLabel>YOUR NEXT GIANT LEAP</SectionLabel><h2 className="mt-4 font-display text-3xl font-bold md:text-5xl">READY TO <GradientText>MAKE AN IMPACT?</GradientText></h2><p className="mt-4 max-w-lg leading-7 text-slate-300">Bring your curiosity. We&apos;ll bring the universe.</p></div><a className="gradient-button shrink-0" href="mailto:hello@nasa-space-apps.eg">JOIN THE MISSION <ArrowRight size={16} /></a></div></Reveal></section>

    <footer id="team" className="footer"><div className="container grid gap-8 py-10 md:grid-cols-3 md:items-end"><div><p className="eyebrow">FOLLOW THE MISSION</p><div className="mt-4 flex gap-2">{[[AtSign,'Instagram'],[Globe,'LinkedIn'],[MessageCircle,'Discord'],[Video,'YouTube'],[Send,'X']].map(([Icon,label]) => <a key={label as string} href="#home" className="social-button" aria-label={label as string}><Icon size={16} /></a>)}</div></div><p className="text-center font-display text-xs tracking-[.24em] text-slate-400">BUILD · COLLABORATE · INSPIRE</p><div className="flex items-center justify-start gap-3 md:justify-end"><span className="logo-mark small"><Rocket size={15} /></span><p className="max-w-[220px] text-right text-[10px] leading-5 tracking-[.12em] text-slate-400">6TH OF OCTOBER CITY, EGYPT — NASA SPACE APPS CHALLENGE 2026</p></div></div></footer>
  </main>
}
